/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/
#include<stdint.h>
void delay();
void clear();
void function1();
void function2();
void function3();
void function4();
void function5();
void blue(int);
void red(int);
void orange(int);
void green(int);
int i,j,k,p,l;

uint32_t *p21=(uint32_t*)0X48001000;
uint32_t *p31=(uint32_t*)0X48001014;
uint32_t *p1=(uint32_t*)0X40021014;
uint32_t *p2=(uint32_t*)0X48001000;
uint32_t *p3=(uint32_t*)0X48001014;
int main()
{
			*p1 |=(1<<21);

			while(1)
			{
				p=1;
				do
				{
				switch(p)
				{
				case 1:
						function1();
						break;

				case 2:
						function2();
						break;

				case 3:
						function3();
						break;
				case 4:
						function4();
						break;

				case 5:
						function5();
						delay();
						clear();
						function5();
						break;

				}
				p++;
				}while(p<=5);
			}
}
void clear()
{
	uint32_t *p21=(uint32_t*)0X48001000;
	uint32_t *p31=(uint32_t*)0X48001014;

	uint32_t *p22=(uint32_t*)0X48001000;
	uint32_t *p32=(uint32_t*)0X48001014;

	*p21 &=00000000;
	*p31 &=00000000;

	*p22 &=00000000;
	*p32 &=00000000;

}
void delay()
{
	int i;
	for(i=300000;i>=0;i--);
}
void blue(int i)
{
	if(i==1)
	{
		*p2 &=~(12<<16);
		*p2 |=(1<<16);
		*p3 |=(1<<8);
	}
	else
	{
		*p2 &=~(12<<24);
		*p2 |=(1<<24);
		*p3 |=(1<<12);
	}
}
void red(int i)
{
	if(i==1)
	{
		*p2 &=~(3<<18);
		*p2 |=(1<<18);
		*p3 |=(1<<9);
	}
	else
	{
		*p2 &=~(3<<26);
		*p2 |=(1<<26);
		*p3 |=(1<<13);
	}
}

void orange(int i)
{
	if(i==1)
	{
		*p2 &=~(12<<20);
		*p2 |=(1<<20);
		*p3 |=(1<<10);
	}
	else
	{
		*p2 &=~(12<<28);
		*p2 |=(1<<28);
		*p3 |=(1<<14);
	}
}
void green(int i)
{
	if(i==1)
	{
		*p2 &=~(3<<22);
		*p2 |=(1<<22);
		*p3 |=(1<<11);
	}
	else
	{
		*p2 &=~(3<<30);
		*p2 |=(1<<30);
		*p3 |=(1<<15);
	}
}
void function1()
{
	i=8,j=12;
	k=i*2;
	while((i>=8)&&(i<=15))
	{
		*p2 &=~(j<<k);
		*p2 |=(1<<k);
		*p3 |=(1<<i);
		++i;
		k=i*2;
		j=(j==12)?3:12;
		delay();
		clear();
	}
	delay();
	clear();
}
void function2()
{
	i=8,j=12,l=3;
	k=i*2;
	while((i>=8)&&(i<=11))
	{
		*p2 &=~(j<<k);
		*p2 |=(1<<k);
		*p3 |=(1<<i);
		*p21 &=~(l<<(k+8));
		*p21 |=(1<<(k+8));
		*p31 |=(1<<(i+4));
		++i;
		k=i*2;
		//j=(j==12)?3:12;
		delay();
		clear();
	}
	delay();
	clear();
}
void function3()
{
	blue(1);
	delay();
	red(1);
	delay();
	orange(1);
	delay();
	green(1);
	delay();
	blue(2);
	delay();
	red(2);
	delay();
	orange(2);
	delay();
	green(2);
	delay();
	clear();
}
void function4()
{
	blue(1);
	delay();
	orange(1);
	delay();
	blue(2);
	delay();
	orange(2);
	delay();
	clear();
	red(1);
	delay();
	green(1);
	delay();
	red(2);
	delay();
	green(2);
	delay();
	clear();
}
void function5()
{
	blue(1);
	red(1);
	orange(1);
	green(1);
	blue(2);
	red(2);
	orange(2);
	green(2);
	delay();
	delay();
	clear();
}
