/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include<stdint.h>
void blue();//PE8 and PE12 pin
void red();///PE9 and PE13 pin
void orange();//PE10 and PE14 pin
void green();//PE11 and PE15 pin
void clear();
void delay();
int main()
{
		while(1)
		{
			uint32_t *p1=(uint32_t*)0X40021014;
			*p1 |=0X00200000;
			while(1)
			{
				blue();
				delay();
				red();
				delay();
				orange();
				delay();
				green();
				delay();
				clear();
				delay();
			}
		}
}
void blue()
{

	uint32_t *p21=(uint32_t*)0X48001000;
	uint32_t *p31=(uint32_t*)0X48001014;

	uint32_t *p22=(uint32_t*)0X48001000;
	uint32_t *p32=(uint32_t*)0X48001014;

	*p21 &=0XFCFFFFFF;
	*p21 |=0X01000000;
	*p31 |=0X1000;

	delay();

	*p22 &=0XFFFCFFFF;
	*p22 |=0X00010000;
	*p32 |=0X0100;

}
void red()
{

	uint32_t *p21=(uint32_t*)0X48001000;
	uint32_t *p31=(uint32_t*)0X48001014;

	uint32_t *p22=(uint32_t*)0X48001000;
	uint32_t *p32=(uint32_t*)0X48001014;

	*p21 &=0XF3FFFFFF;
	*p21 |=0X04000000;
	*p31 |=0X2000;

	delay();

	*p22 &=0XFFF3FFFF;
	*p22 |=0X00040000;
	*p32 |=0X0200;

}
void orange()
{

	uint32_t *p21=(uint32_t*)0X48001000;
	uint32_t *p31=(uint32_t*)0X48001014;

	uint32_t *p22=(uint32_t*)0X48001000;
	uint32_t *p32=(uint32_t*)0X48001014;

	*p21 &=0XCFFFFFFF;
	*p21 |=0X10000000;
	*p31 |=0X4000;

	delay();

	*p22 &=0XFFCFFFFF;
	*p22 |=0X00100000;
	*p32 |=0X0400;

}
void green()
{
	uint32_t *p21=(uint32_t*)0X48001000;
	uint32_t *p31=(uint32_t*)0X48001014;

	uint32_t *p22=(uint32_t*)0X48001000;
	uint32_t *p32=(uint32_t*)0X48001014;

	*p21 &=0X3FFFFFFF;
	*p21 |=0X40000000;
	*p31 |=0X8000;

	delay();

	*p22 &=0XFF3FFFFF;
	*p22 |=0X00400000;
	*p32 |=0X0800;

}
void clear()
{
	uint32_t *p21=(uint32_t*)0X48001000;
	uint32_t *p31=(uint32_t*)0X48001014;

	uint32_t *p22=(uint32_t*)0X48001000;
	uint32_t *p32=(uint32_t*)0X48001014;

	*p21 &=00000000;
	*p31 &=00000000;

	*p22 &=00000000;
	*p32 &=00000000;

}
void delay()
{
	int i;
	for(i=3000000;i>=0;i--);
}
